# Generated by Django 2.0.6 on 2018-06-27 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefscargo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('flavor_profile', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=32)),
                ('descriptor', models.CharField(blank=True, max_length=32)),
                ('prep_descriptor', models.CharField(blank=True, max_length=64)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chefscargo.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.TextField()),
                ('cook_time', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(through='chefscargo.IngredientQuantity', to='chefscargo.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chefscargo.Recipe'),
        ),
    ]
