# Generated by Django 2.0.6 on 2018-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefscargo', '0002_grouprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
